import type { Metadata } from "next";
import { Roboto } from "@next/font/google";
import "./globals.css";
import { 
  ClerkProvider,
  SignInButton, 
  SignedIn, 
  SignedOut, 
  UserButton 
} from "@clerk/nextjs";
import Provider from "./provider";

// Initialize the Roboto font with specific subsets and weight
const roboto = Roboto({
  subsets: ["latin"],
  weight: '400',
});

// Apply the Roboto font to the body element by adding it to the className
// This ensures the font is used in the layout
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { // Fixed the closing parenthesis

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={roboto.className}> {/* Apply the Roboto font class */}
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          <Provider>
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  ); // Fixed the closing parenthesis
}